In [6]:

import pandas as pd
import time
import requests
import json

import pymssql

In [5]:
defect = pd.read_csv("defect.csv")

defect.head()

,name,defectid
0,LJ6406953A42C000000000000A044FC012078410,6b35f021556c4126a88592949ed40479_10.200.218.127
1,LJ6406953A42C000000000000A044FC012078810,9c5436add6ac4534ab3985de43e46e11_10.200.218.127
2,LJ6406953A42C000000000000A044FC012079510,6159b4a921a24a68a64c97fb1c0e2365_10.200.218.127
3,LJ6406953A42C000000000000A044FC012078010,8fe1fdb4ab1c485683c4bc38358fcdca_10.200.218.127
4,LJ6406953A42C000000000000A044FC012140210,8785c42e0a5247a48fed9daf6a268965_10.200.218.127

In [7]:
def get_conn(host, user, password, database):
    """
    Creates a connection to a database using the provided host, username, password, and database name.

    Parameters:
        host (str): The host name or IP address of the database server.
        user (str): The username used to authenticate with the database server.
        password (str): The password used to authenticate with the database server.
        database (str): The name of the database to connect to.

    Returns:
        conn (pymssql.Connection): A connection object representing the connection to the database.
    """
    try:
        conn = pymssql.connect(
            server=host,
            user=user,
            password=password,
            database=database,
            as_dict=True,
        )
    # 捕获数据库连接错误
    except Exception as e:
        print(e)

    return conn
Host = "10.80.65.109"
User = "datalab"
Password = "cx3x#x&W"
Database = "IAData"
conn =  get_conn(Host,User,Password,Database)

In [12]:
sql = f""" SELECT defectid,FVBucketName,FVFileName FROM dbo.defect where defectid in {tuple(defect["defectid"].values)}	"""

cursor = conn.cursor()
cursor.execute(sql)
channelkeys = cursor.fetchall()

channelkeys

[{'defectid': '0189c2e8c30847ef80f13bf9ad9d329e_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '4e916f288f0642dbb51081627191a646'},
 {'defectid': '054f3e32c68e4cd7b3f0581aea22ffde_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'e793206a34f54e32a17d63e241d9ad5b'},
 {'defectid': '22c58011b9ad4fa68068a97a74eb5ba4_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '0e804167ac434796bdefd0bf8d14001c'},
 {'defectid': '233ad76c96a440c2abe2250e50fe78c3_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'd75830fde0b04668888bc38e8940096d'},
 {'defectid': '2af7a7a27d444b7fb51cec78ec89ef09_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'b3e7bdbe0e4442febe7670264f938dfe'},
 {'defectid': '2bfbe09239ed46419478663dccb3d5c8_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '3c0b7aabbba24e9b972e4ca59b0e4c2d'},
 {'defectid': '2bfe85eb5ff647ec8f1fda31ad75edb2_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '8239df92f2f34b238b6e884fdcd62eb9'},
 {'defectid': '2c5107a19321493d98b6db45a118fd04_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '2766f19bb8454b9b809bc304aa5209c4'},
 {'defectid': '2c9e2b08c7bd420fadc37636950939bc_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '0759154e9b0f49d196e380f399ddcaef'},
 {'defectid': '3a22f3f323974e789a20788ea8d20420_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '23bd3d5010bf4178b9b83e50df1c8d90'},
 {'defectid': '3a47b22fc1424505b056cf5f5922d1a3_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'fa9d14bb9aae4041973a31956dd12bb0'},
 {'defectid': '53dc31a03fa8496699f35f6fdce67ef4_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '221dd380ea15467587d5caac9fae670b'},
 {'defectid': '5556b09f04f94d039f4ed0b09d823b9f_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'de4d58d433e94c979853c3cd2dbfffe1'},
 {'defectid': '6159b4a921a24a68a64c97fb1c0e2365_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '36b9cec7750b4c8a928157b52617f110'},
 {'defectid': '639f34badc90478082cb5494c29cac0d_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '509f9034e3c74e2ca7b9e280ddb72ea1'},
 {'defectid': '6b35f021556c4126a88592949ed40479_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '7192b5180f654fe3b890c5e8ceb2a04c'},
 {'defectid': '6c643bc17b4742acacb12ef2a8b45feb_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '5d87855f67524b51bbc264a947662c95'},
 {'defectid': '7b351a1f0aa549008bcaec154dbcb7c6_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '5c1de950dd6040a39a5fcd850fba37b0'},
 {'defectid': '7bf67a09a9f447ee926abca755cc323a_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '2a400d82daa04ef983311d9ecfa4e5ee'},
 {'defectid': '8785c42e0a5247a48fed9daf6a268965_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '0ad504ffb87645b8844a8a54a356f5fa'},
 {'defectid': '88beea06e1a24aad85d50606eb7774c0_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '1dba24c0b5b94e4f916a1dc2641dabfc'},
 {'defectid': '8ef51a7e200e4d09b2d5da9d48e6149d_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '62759b80912f40cea815efcb1b0a074b'},
 {'defectid': '8fe1fdb4ab1c485683c4bc38358fcdca_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'adda126d060b4ac181b7380aac6d821d'},
 {'defectid': '905cb2f7a8534e93a92de746d85bd4c2_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '518e7ad6db3c4bcdab9a83baa5f5f45a'},
 {'defectid': '906b1a48f117463dad28d2da6216233b_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'fbb2b4b9849949969ab372ad1eba910c'},
 {'defectid': '9c5436add6ac4534ab3985de43e46e11_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '971fe6c6fe1a45c9a0c513fbbf608c23'},
 {'defectid': 'a7fd7b0e6b6745ffbd0f9b3e33609f56_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '9e9071381cd845d289d0efdf9208446e'},
 {'defectid': 'c2ff05efeb764f9fb621da06a7bd6823_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '83c6aef1d4714737957f8d2bfa0a26cb'},
 {'defectid': 'c48f4131fd394ae881b1b1493c4c7741_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'b6dc2d4c609d4ea8b2454183779e4577'},
 {'defectid': 'cf0bbd9eeaa740839c5407199a5bf0fd_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '6604b9c468bf42e590246e5816885581'},
 {'defectid': 'd55cd384168a4d379c2163609844166a_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '6b22a01373644c7482174a9894eca32a'},
 {'defectid': 'd6f147d38a9a4da0a93082483bd7d804_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'afbb02fa3bae40dd973e41cf4714586f'},
 {'defectid': 'd76927bf4a6d40508c86ef13f713235f_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'c7c164bc6af0448fb1be3576554741ae'},
 {'defectid': 'e4f4d2d1df2147eb89af6cfa04e7847c_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'c3a87fe96ced4008a4bebcd9d480de12'},
 {'defectid': 'e72041c3bc254204a6478f369465998c_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'ef2bb934e7c04d7d9b6efea653048c4c'},
 {'defectid': 'e94e23fab30e498b868ac24561a2493a_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '0c8a920584d94fae878c62aa6d3fa695'},
 {'defectid': 'ea3fe7efc7464168b1d760456229b0e0_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'ad3bab229d0e4a549583b026bf45d520'},
 {'defectid': 'eea9db39288c4af9bddcc948a2d71c3a_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '0900faef5e6a446bb91c35bbb7d7f49c'},
 {'defectid': 'f4b6c8bb62374ed691f749b5b3c6a3bb_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': '58bb7c1d02da4ef18de417f7df8fde72'},
 {'defectid': 'ff3091cc6c90498f802e7fceaafd558d_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'fc89fc6fb7b84a1196577fb09724828a'},
 {'defectid': 'ff76aa6ab3fd438886ca0dbe19ae5213_10.200.218.127',
  'FVBucketName': 'sa-42c-202406',
  'FVFileName': 'f4aa7b3ae0604b7681cb59d8fccef363'}]

In [13]:
def get_json(defects):
    """
    Retrieves JSON data from a list of defects.

    Args:
        defects (list): A list of dictionaries representing defects.

    Returns:
        pandas.DataFrame: A DataFrame containing the JSON data from the defects.
    """
    # logger.info(f"defects点列表的长度：{len(defects)}")

    json_data_list = []
    start = time.time()

    for d in defects:
        try:
            FVBucketName = d["FVBucketName"]
            FVFileName = d["FVFileName"]

            url = f"http://10.211.89.15:9008/SAS3API/api/Storage/sa/{FVBucketName}/{FVFileName}?filetype=json"
            response = requests.get(url, timeout=10)
            json_data = json.loads(response.text)
            # json_data["frameid"] = d["frameid"]
            json_data["defectid"] = d["defectid"]
            # json_data["label"] = d["Defect_RE_result"]
            json_data_list.append(json_data)
        except requests.exceptions.Timeout:
            print("请求超时")
        except json.decoder.JSONDecodeError:
            print("JSON解码错误")
            print(f"FVBucketName, FVFileName: {FVBucketName}, {FVFileName}")
            print(response.text)
        except Exception as e:
            print(e)

    df = pd.DataFrame(json_data_list)

    print(f"程序运行时间：{time.time() - start} s")

    return df
df =   get_json(channelkeys)

程序运行时间：0.4289276599884033 s

In [14]:
df.hea

,flawArea,flawCustomType,flawLength,flawWidth,area,roundness,numConnected,circularity,rect2Phi,rect2Len1,...,regionbackgroundMeangraydiff,regionmeanwidth,regionlinearity,defectid,highgraydiffarea2defectareaRatio1,highgraydiffarea2defectareaRatio2,highgraydiffarea2defectareaRatio3,highgraydiffarea2defectareaRatio4,highgraydiffarea2defectareaRatio5,
0,0.11,S1V1-线性划伤,1.05,0.29,744,0.45356,2,0.104809,57.6526,87.3687,...,65.0387,8.51564,0.888864,0189c2e8c30847ef80f13bf9ad9d329e_10.200.218.127,NaN,NaN,NaN,NaN,NaN,NaN
1,0.01,S1V2-残胶,0.13,0.13,84,0.830317,1,0.789229,45,10.8995,...,68.4338,7.70678,0.012168,054f3e32c68e4cd7b3f0581aea22ffde_10.200.218.127,0.952268,0.845137,0.738007,0.583264,0.49994,NaN
2,0.02,S2V5-VA油墨点,0.22,0.15,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,22c58011b9ad4fa68068a97a74eb5ba4_10.200.218.127,NaN,NaN,NaN,NaN,NaN,
3,0.01,S2V5-VA油墨点,0.15,0.10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,233ad76c96a440c2abe2250e50fe78c3_10.200.218.127,NaN,NaN,NaN,NaN,NaN,
4,0.04,S1V2-视窗刺伤,0.35,0.20,304,0.68487,1,0.416205,33.6901,29.0124,...,87.4418,10.4783,0.307392,2af7a7a27d444b7fb51cec78ec89ef09_10.200.218.127,0.996678,0.98681,0.947337,0.868392,0.759843,NaN

In [15]:
final_data = pd.merge(defect, df, on="defectid")
final_data.head()

,name,defectid,flawArea,flawCustomType,flawLength,flawWidth,area,roundness,numConnected,circularity,...,area2smallestRectRatio,regionbackgroundMeangraydiff,regionmeanwidth,regionlinearity,highgraydiffarea2defectareaRatio1,highgraydiffarea2defectareaRatio2,highgraydiffarea2defectareaRatio3,highgraydiffarea2defectareaRatio4,highgraydiffarea2defectareaRatio5,
0,LJ6406953A42C000000000000A044FC012078410,6b35f021556c4126a88592949ed40479_10.200.218.127,0.01,S1V2-残胶,0.12,0.10,56,0.778979,1,NaN,...,0.7,59.4149,5.6,0.0234132,0.85699,0.714158,0.553473,0.499911,0.482057,NaN
1,LJ6406953A42C000000000000A044FC012078810,9c5436add6ac4534ab3985de43e46e11_10.200.218.127,0.01,S1V2-残胶,0.12,0.10,60,0.69191,1,NaN,...,0.75,31.8291,6,0.0575301,0.783203,0.566572,0.349942,0.29995,0.183303,NaN
2,LJ6406953A42C000000000000A044FC012079510,6159b4a921a24a68a64c97fb1c0e2365_10.200.218.127,0.01,S1V2-残胶,0.10,0.07,44,0.772208,1,0.714302,...,0.916667,63.5769,5.5,0.0979077,0.74983,0.545331,0.43172,0.363554,0.340832,NaN
3,LJ6406953A42C000000000000A044FC012078010,8fe1fdb4ab1c485683c4bc38358fcdca_10.200.218.127,0.01,S1V2-残胶,0.14,0.10,80,0.79758,1,NaN,...,0.833333,64.8855,6.66667,0.148714,0.96238,0.837395,0.699913,0.612423,0.474941,NaN
4,LJ6406953A42C000000000000A044FC012140210,8785c42e0a5247a48fed9daf6a268965_10.200.218.127,0.02,S1V1-线性划伤,0.35,0.13,140,0.568718,2,0.18565,...,0.453953,56.3301,4.75646,0.754549,0.885651,0.742804,0.542818,0.449968,0.328548,NaN

In [17]:
final_data.to_csv("final_data.csv",index=False,encoding="utf-8-sig")